### ISSUE TITLE
Bug after installing v1.10 or v1.12

### ISSUE THREAD

**Issue by eze92** [v-atamanenko/osu-octave#13]
When opening the application an error appears C-12828-1 with the base version, no problem

**Comment by takoyaki99** [comment]
Have you put the data files in? Those seem to be required, as per my experience~

**Comment by v-atamanenko** [comment]
@eze92 please make sure that you also updated the data files (in particular, the `skins` folder update is required)

**Comment by v-atamanenko** [comment]
> thanks I did what you mentioned and it worked, will I have to perform this procedure with each update?
I'll do my best to keep data files compatibility in place in next releases.
