### ISSUE TITLE
Crash on maps with negative first msPerBeat in timing points and more

### ISSUE THREAD

**Issue by v-atamanenko** [v-atamanenko/osu-octave#14]
Reddit user [Streakdreniline](https://www.reddit.com/user/Streakdreniline/) experienced crashes while adding their beatmaps. They shared the archive of their beatmaps and I was able to pinpoint that three of ~656 beatmaps were causing crashes due to:

- Beatmap having negative first msPerBeat value in timing points (this is invalid according to the format specification)
— Beatmap having sliders with no curve points
— OsuParser incorrectly processing audio filename in extras (trying to convert it to integer)

**Comment by v-atamanenko** [comment]
[osu-octave.vpk.zip](https://github.com/v-atamanenko/osu-octave/files/8465349/osu-octave.vpk.zip)
Test build with bugfix

**Comment by v-atamanenko** [comment]
Confirmed to be working now by [@Streakdreniline](https://www.reddit.com/user/Streakdreniline/) 👍🏽

**Comment by Takatsuki** [comment]
I tried the bugfix build, but I'm still experiencing crashes when trying to load songs. Please check the Reddit thread for the song pack that I posted and please see if you can figure out what's causing the issue.
