### ISSUE TITLE
Questions about how you made it.

### ISSUE THREAD

**Issue by KirgoPlayer** [v-atamanenko/osu-octave#19]
Hello! Sorry for bothering you.... This isn't an issue is more of a question. Do you have an email/social media where I can ask you the question? The question isn't about the port more about how you made it.

Kind regards, Kirgo

**Comment by v-atamanenko** [comment]
@KirgoPlayer preferably discord gl33ntwine#7290 or twitter @gl33ntwine

**Comment by KirgoPlayer** [comment]
> @KirgoPlayer preferably discord gl33ntwine#7290 or twitter @gl33ntwine

Thank you!
