### ISSUE TITLE
Implement support for translations

### ISSUE THREAD

**Issue by kuragehimekurara1** [v-atamanenko/osu-octave#2]
I would like to translate osu! Octave into Japanese. Does osu! Octave support translation?

**Comment by takoyaki99** [comment]
あたしは翻訳にお手伝いできます！

**Comment by kuragehimekurara1** [comment]
> あたしは翻訳にお手伝いできます！

自分も日本語翻訳出来ます！

**Comment by kuragehimekurara1** [comment]
> あたしは翻訳にお手伝いできます！
> 
> > 4/9/22 午後12:22、kuragehime ***@***.***>のメール:
> > 
> > ﻿
> > I would like to translate osu! Octave into Japanese. Does osu! Octave support translation?
> > 
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you are subscribed to this thread.
> 

また翻訳をお手伝い出来ることを伝えてくれてありがとうございます！

**Comment by v-atamanenko** [comment]
Hi! *Right now* that would be possible by editing strings directly in the code and recompiling. But that's obviously a bad way to handle things...
I will roll out an adequate translation support within a week or two, so stay tuned!
Thanks!

**Comment by kuragehimekurara1** [comment]
> Hi! *Right now* that would be possible by editing strings directly in the code and recompiling. But that's obviously a bad way to handle things...
> 
> I will roll out an adequate translation support within a week or two, so stay tuned!
> 
> Thanks!

OK!  Thank you for your translation support!

**Comment by v-atamanenko** [comment]
Implemented in version 1.20.
