### ISSUE TITLE
beatmap not loading in game

### ISSUE THREAD

**Issue by ikzouo** [v-atamanenko/osu-octave#4]
downloaded beatmap  at osu.ppy.sh  and stored in the correct location

but  beatmap not loading in game

![image](https://user-images.githubusercontent.com/36393635/162596703-d0f62b2e-36b0-4193-9e2a-31e6af961fd9.png)

![image](https://user-images.githubusercontent.com/36393635/162596509-8e92c2b7-3d99-4756-a4f0-436f51319b0a.png)

![image](https://user-images.githubusercontent.com/36393635/162596524-8f24b1d2-0766-498b-91a3-7f04942dd843.png)

**Comment by v-atamanenko** [comment]
Hi. It's an osu!mania beatmap. Only osu!standard beatmaps are supported.

**Comment by ikzouo** [comment]
> Hi. It's an osu!mania beatmap. Only osu!standard beatmaps are supported.

oh I got it  thanks
